export const taskList = [
  {
    doType: "乘坐",
    name: "氢能公交",
    resultDo: "代替",
    sth: "传统大巴",
    key: "hydrogenBus",
    value: "446",
  },
  {
    doType: "骑行",
    name: "氢能自行车",
    resultDo: "代替",
    sth: "燃油车",
    key: "hydrogenBicycle",
    value: "620",
  },
  {
    doType: "体验",
    name: "充电座椅",
    resultDo: "",
    sth: "",
    key: "hydrogenChair",
    value: "12.3",
  },
  {
    doType: "走",
    name: "发电步道",
    resultDo: "产生",
    sth: "3度电",
    key: "electricTrail",
    value: "26.4",
  },
  {
    doType: "体验",
    name: "零碳单车",
    resultDo: "产生",
    sth: "6度电",
    key: "carbonBicycle",
    value: "26.83",
  },
  {
    doType: "饮用",
    name: "海露水",
    resultDo: "代替",
    sth: "普通纯净水",
    key: "drinkWater",
    value: "1.6",
  },
  {
    doType: "体验",
    name: "零碳小屋",
    resultDo: "",
    sth: "",
    key: "carbonRoom",
    value: "510",
  },
];
