export const taskList = [
  {
    id: 0,
    title: "氢能大巴打卡",
    description: "体验并打卡即可获得零碳积分",
    key: "hydrogenBus",
    icon: "../../static/taskList2.png",
    completed: false,
    type: "checkin",
  },
  {
    id: 1,
    title: "氢能自行车打卡",
    description: "体验并打卡即可获得零碳积分",
    key: "hydrogenBicycle",
    icon: "../../static/taskList2.png",
    completed: false,
  },
  {
    id: 2,
    title: "光伏充电座椅打卡",
    description: "体验并打卡即可获得零碳积分",
    key: "hydrogenChair",
    icon: "../../static/taskList2.png",
    completed: false,
  },
  {
    id: 3,
    title: "走电步道打卡",
    description: "体验并打卡即可获得零碳积分",
    key: "electricTrail",
    icon: "../../static/taskList2.png",
    completed: false,
  },
  {
    id: 4,
    title: "喝海露水打卡",
    description: "体验并打卡即可获得零碳积分",
    key: "drinkWater",
    icon: "../../static/taskList2.png",
    completed: false,
  },
  {
    id: 5,
    title: "体验零碳单车打卡",
    description: "体验并打卡即可获得零碳积分",
    key: "carbonBicycle",
    icon: "../../static/taskList2.png",
    completed: true,
  },
  {
    id: 6,
    title: "零碳小屋打卡",
    description: "体验并打卡即可获得零碳积分",
    key: "carbonRoom",
    icon: "../../static/taskList2.png",
    completed: true,
  },
  {
    id: 7,
    title: "每日任务·知识问答",
    description: "参与问答可获得1-5点零碳积分",
    key: "question",
    icon: "../../static/taskList1.png",
    completed: false,
  },
  {
    id: 8,
    title: "每日任务·浏览文章",
    description: "阅读文章可获得5点零碳积分",
    key: "article",
    icon: "../../static/taskList3.png",
    completed: false,
  },
];
